name: Integration Test

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Postgres and Config
        run: |
          sudo apt-get install postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          sudo systemctl status postgresql
          sudo su - postgres -c "psql -c \"CREATE DATABASE ${{ secrets.POSTGRES_DATABASENAME }};\""
          sudo su - postgres -c "psql -c \"ALTER USER ${{secrets.POSTGRES_USERNAME}} WITH PASSWORD '${{ secrets.POSTGRES_PASSWORD }}';\""
          sudo su - postgres -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.POSTGRES_DATABASENAME }} TO ${{ secrets.POSTGRES_USERNAME }};\""

      - name: Wait for Application Startup
        run: sleep 10s
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/cloud
          SPRING_DATASOURCE_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Run integration tests
        run: mvn clean verify