name: validation

on:
  pull_request:
    branches: [ "master" ]

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Get Credentials'
        run: echo $GOOGLE_APPLICATION_CREDENTIALS

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

  validate:
    needs: job_id
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup

      - name: 'Authenticate with Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Create test deployment folder
        run: |
          mkdir -p CloudAppRelease

      - name: Create zip of test deployment folder
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r webapp.zip CloudAppRelease

      - name: Run `packer init`
        id: init
        run: "packer init packer-info.pkr.hcl"

      - name: Run `packer fmt`
        id: fmt
        run: "packer fmt -check packer-info.pkr.hcl"

      - name: Validate Packer Image
        run: packer validate \
            -var "project_id=${PROJECT_ID}" \
            -var "ssh_username=packer" \
            -var "vm_size=e2-small" \
            -var "image_family=custom-centos-8-image-webapp" \
            -var "source_image_family=centos-stream-8" \
            -var "zone=us-central1-a" \
            -var "vpc_network=default" \
            -var "database_user=${DATABASE_USER}" \
            -var "database_password=${DATABASE_PASSWORD}" \
              packer-info.pkr.hcl